import { Component, inject } from '@angular/core';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { FormsModule } from '@angular/forms';
import { AddMember } from './components/add-member/add-member';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { Member } from './components/member/member';
import { DeleteMember } from './components/delete-member/delete-member';
import { AddCurso } from './components/add-curso/add-curso';
import { CursosMember } from './components/cursos-member/cursos-member';

interface Socio {
  id: string;
  nombres: string;
  apellidos: string;
  correo: string;
  tel: string;
  dni: string;
  estado: string;
  fechaVenc: string;
  profesor: string;
  contrasena: string;
  cursos: number[];
  selected: boolean;
}

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [
    MatDialogModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatChipsModule,
    CommonModule,
    FormsModule,
  ],
  templateUrl: './main-layout.html',
  styleUrl: './main-layout.scss',
})
export class MainLayout {
  private dialog = inject(MatDialog);
  private router = inject(Router);

  filtrosAbiertos = false;
  sortColumn: 'nombres' | 'apellidos' | null = null;
  sortAsc = true;
  estadoFiltro: 'todos' | 'Activo' | 'Inactivo' = 'todos';
  profesorFiltro: 'todos' | 'Si' | 'No' = 'todos';
  textoBusqueda = '';

  filtros = [
    { label: 'Activo', activo: false },
    { label: 'Inactivo', activo: false },
    { label: 'Profesor', activo: false },
    { label: 'A → Z', activo: false },
    { label: 'Z → A', activo: false },
    { label: '0 → 9', activo: false },
    { label: '9 → 0', activo: false },
  ];

  socios: Socio[] = [
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Martínez López',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },
    {
      id: '01',
      nombres: 'Felipe Carlos',
      apellidos: 'Guzmán Segundo',
      correo: 'FelipeCarlosGuzman@gmail.com',
      tel: '+34 652 25 35 97',
      dni: '52316377W',
      estado: 'Activo',
      fechaVenc: '05/01/2027',
      profesor: 'Si',
      contrasena: 'vW2O8a9z7',
      cursos: [],
      selected: false,
    },
    {
      id: '02',
      nombres: 'Ana',
      apellidos: 'Castillo Luisiana',
      correo: 'ana@gmail.com',
      tel: '+34 611 11 11 11',
      dni: '12345678A',
      estado: 'Inactivo',
      fechaVenc: '01/01/2026',
      profesor: 'No',
      contrasena: 'pass123',
      cursos: [],
      selected: false,
    },
    {
      id: '03',
      nombres: 'Carlos',
      apellidos: 'Rodríguez Peña',
      correo: 'carlos.rodriguez@gmail.com',
      tel: '+34 634 87 21 09',
      dni: '47823651B',
      estado: 'Activo',
      fechaVenc: '12/06/2027',
      profesor: 'No',
      contrasena: 'cRod#2025',
      cursos: [],
      selected: false,
    },
    {
      id: '04',
      nombres: 'Laura',
      apellidos: 'Sánchez Vidal',
      correo: 'laura.sanchez@hotmail.com',
      tel: '+34 699 44 55 66',
      dni: '38291047C',
      estado: 'Activo',
      fechaVenc: '20/03/2027',
      profesor: 'Si',
      contrasena: 'lSanVid9!',
      cursos: [],
      selected: false,
    },
    {
      id: '05',
      nombres: 'Javier',
      apellidos: 'Torres Blanco',
      correo: 'javier.torres@yahoo.es',
      tel: '+34 612 33 44 55',
      dni: '29384756D',
      estado: 'Inactivo',
      fechaVenc: '15/09/2025',
      profesor: 'No',
      contrasena: 'jTorres77',
      cursos: [],
      selected: false,
    },
    {
      id: '06',
      nombres: 'María Isabel',
      apellidos: 'Fernández Ruiz',
      correo: 'mifernandez@gmail.com',
      tel: '+34 677 88 99 00',
      dni: '61728394E',
      estado: 'Activo',
      fechaVenc: '01/11/2027',
      profesor: 'Si',
      contrasena: 'MiFer#321',
      cursos: [],
      selected: false,
    },
    {
      id: '07',
      nombres: 'David',
      apellidos: 'García Moreno',
      correo: 'david.garcia@gmail.com',
      tel: '+34 655 12 34 56',
      dni: '73849201F',
      estado: 'Activo',
      fechaVenc: '28/02/2027',
      profesor: 'No',
      contrasena: 'dGarM0r3',
      cursos: [],
      selected: false,
    },
    {
      id: '08',
      nombres: 'Sofía',
      apellidos: 'Jiménez Castillo',
      correo: 'sofia.jimenez@outlook.com',
      tel: '+34 622 76 54 32',
      dni: '84930127G',
      estado: 'Inactivo',
      fechaVenc: '10/04/2025',
      profesor: 'No',
      contrasena: 'sJim2024!',
      cursos: [],
      selected: false,
    },
    {
      id: '09',
      nombres: 'Alejandro',
      apellidos: 'López Herrera',
      correo: 'alopez.herrera@gmail.com',
      tel: '+34 691 23 45 67',
      dni: '95012834H',
      estado: 'Activo',
      fechaVenc: '17/08/2027',
      profesor: 'Si',
      contrasena: 'aLopH3rr',
      cursos: [],
      selected: false,
    },
    {
      id: '10',
      nombres: 'Carmen',
      apellidos: 'Navarro Gil',
      correo: 'carmen.navarro@gmail.com',
      tel: '+34 645 67 89 01',
      dni: '06182345I',
      estado: 'Activo',
      fechaVenc: '30/06/2027',
      profesor: 'No',
      contrasena: 'cNavG1l9',
      cursos: [],
      selected: false,
    },
    {
      id: '11',
      nombres: 'Pablo',
      apellidos: 'Díaz Serrano',
      correo: 'pablo.diaz@gmail.com',
      tel: '+34 663 11 22 33',
      dni: '17263849J',
      estado: 'Inactivo',
      fechaVenc: '05/12/2025',
      profesor: 'No',
      contrasena: 'pDiaz$56',
      cursos: [],
      selected: false,
    },
    {
      id: '12',
      nombres: 'Elena',
      apellidos: 'Romero Fuentes',
      correo: 'elena.romero@hotmail.com',
      tel: '+34 608 99 88 77',
      dni: '28374950K',
      estado: 'Activo',
      fechaVenc: '22/10/2027',
      profesor: 'Si',
      contrasena: 'eRomFu22',
      cursos: [],
      selected: false,
    },


  ];

  get sociosFiltrados(): Socio[] {
    let lista = this.socios;

    if (this.estadoFiltro !== 'todos') {
      lista = lista.filter(s => s.estado === this.estadoFiltro);
    }

    if (this.profesorFiltro !== 'todos') {
      lista = lista.filter(s => s.profesor === this.profesorFiltro);
    }

    if (this.textoBusqueda.trim()) {
      const texto = this.textoBusqueda.toLowerCase().trim();
      lista = lista.filter(s =>
        s.nombres.toLowerCase().includes(texto)   ||
        s.apellidos.toLowerCase().includes(texto) ||
        s.correo.toLowerCase().includes(texto)    ||
        s.dni.toLowerCase().includes(texto)
      );
    }

    return lista;
  }

  get allSelected(): boolean {
    return this.sociosFiltrados.length > 0 && this.sociosFiltrados.every(s => s.selected);
  }

  get someSelected(): boolean {
    return this.sociosFiltrados.some(s => s.selected) && !this.allSelected;
  }

  get selectedSocios(): Socio[] {
    return this.socios.filter(s => s.selected);
  }

  toggleAll(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.sociosFiltrados.forEach(s => (s.selected = checked));
  }

  onCheckChange(): void {}

  filtrarEstado() {
    if (this.estadoFiltro === 'todos') {
      this.estadoFiltro = 'Activo';
    } else if (this.estadoFiltro === 'Activo') {
      this.estadoFiltro = 'Inactivo';
    } else {
      this.estadoFiltro = 'todos';
    }
  }

  filtrarProfesor() {
    if (this.profesorFiltro === 'todos') {
      this.profesorFiltro = 'Si';
    } else if (this.profesorFiltro === 'Si') {
      this.profesorFiltro = 'No';
    } else {
      this.profesorFiltro = 'todos';
    }
  }

  sortBy(col: 'nombres' | 'apellidos') {
    if (this.sortColumn === col) {
      this.sortAsc = !this.sortAsc;
    } else {
      this.sortColumn = col;
      this.sortAsc = true;
    }
    this.socios.sort((a, b) => {
      const valA = a[col].toLowerCase();
      const valB = b[col].toLowerCase();
      return this.sortAsc ? valA.localeCompare(valB) : valB.localeCompare(valA);
    });
  }

  toggleFiltros() {
    this.filtrosAbiertos = !this.filtrosAbiertos;
  }

  toggleChip(filtro: any) {
    filtro.activo = !filtro.activo;
  }

  openAddMember(socio?: Socio) {
    const dialogRef = this.dialog.open(AddMember, {
      width: '480px',
      data: socio ?? null,
    });
    dialogRef.afterClosed().subscribe((result) => {
      if (!result) return;
      if (socio) {
        const index = this.socios.indexOf(socio);
        this.socios[index] = { ...socio, ...result };
      } else {
        this.socios.push(result);
      }
    });
  }

  openMember(socio?: Socio) {
    const esNuevo = !socio;
    const dialogRef = this.dialog.open(Member, {
      width: '480px',
      data: socio ?? null,
    });

    dialogRef.afterClosed().subscribe((result) => {
      if (!result) return;

      if (esNuevo) {
        this.socios.push({
          id: String(this.socios.length + 1).padStart(2, '0'),
          nombres:    result.nombres,
          apellidos:  result.apellidos,
          correo:     result.correo,
          tel:        result.tel,
          dni:        result.dni,
          estado:     result.estado ?? 'Activo',
          fechaVenc:  '',
          profesor:   result.profesor ?? 'No',
          contrasena: '',
          cursos:     [],
          selected:   false,
        });
      } else {
        const index = this.socios.indexOf(socio!);
        this.socios[index] = { ...socio!, ...result };
      }
    });
  }

  onEliminar(socio?: Socio) {
    const dialogRef = this.dialog.open(DeleteMember, { width: '400px' });
    dialogRef.afterClosed().subscribe((confirmed) => {
      if (!confirmed) return;
      if (socio) {
        this.socios = this.socios.filter(s => s !== socio);
      } else {
        this.socios = this.socios.filter(s => !s.selected);
      }
    });
  }

  onCurso(socio: Socio) {
    const dialogRef = this.dialog.open(CursosMember, {
      width: '440px',
      data: { cursosActuales: socio.cursos },
    });
    dialogRef.afterClosed().subscribe((result: number[]) => {
      if (!result) return;
      const index = this.socios.indexOf(socio);
      this.socios[index] = { ...socio, cursos: result };
    });
  }

  goToRegister() {
    this.router.navigate(['/register']);
  }

  openAddCurso() {
    this.dialog.open(AddCurso, { width: '400px' });
  }

  onPagos() {
    console.log('Pagos');
  }

  onCorreo() {
    console.log('Correo', this.selectedSocios);
  }
}
